<?xml version="1.0" encoding="GB2312"?>
<ucmframe name="即开即通服务模块">
   <module file="com/ai/sacenter/shcmcc/UcmGlobalPlaning.xml"    name = "开通测模块" use="false"/>
   <module file="com/ai/sacenter/shcmcc/UcmCbossMapping.xml"     name = "开通测模块" use="true"/>
   <module file="com/ai/sacenter/shcmcc/UcmMicroMapping.xml"     name = "开通测模块" use="true"/>
   <module file="com/ai/sacenter/shcmcc/UcmGsmNSRMapping.xml"    name = "开通测模块" use="true"/>
   <module file="com/ai/sacenter/shcmcc/UcmJTProMapping.xml"     name = "营业测模块" use="true"/>
   <module file="com/ai/sacenter/shcmcc/UcmOthMapping.xml"       name = "营业测模块" use="true"/>
   <module file="com/ai/sacenter/shcmcc/UcmGsmMapping.xml"       name = "营业测模块" use="true"/>
   <module file="com/ai/sacenter/shcmcc/UcmVpnMapping.xml"       name = "营业测模块" use="true"/>
   <module file="com/ai/sacenter/shcmcc/UcmCSfMapping.xml"       name = "开通测模块" use="true"/>
   <module file="com/ai/sacenter/shcmcc/UcmSffMapping.xml"       name = "营业测模块" use="true"/>
</ucmframe>